version: '1.0'
services:

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.26
    container_name: mysql-ssi-school
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/dev/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mysecretpassword --execute \"SHOW DATABASES;\""
      interval: 100s
      retries: 10
    networks:
      - ssi-school


networks:
  ssi-school:
    driver: bridge

volumes:
  mysql:
